### ISSUE TITLE
Regarding the Assumption of Continuous Growth in Application Data Packet Lengths

### ISSUE THREAD

**Issue by CigarOVO** [royweiss1/GPT_Keylogger#3]
Hello, thank you for sharing your paper and making the code publicly available! After studying your paper and implementation, I came across a question I’d like to clarify:

The paper mentions that the length of application data packets tends to show a pattern of continuous growth. However, I’ve observed that not all cases follow this assumption. For instance, as shown in the figures, there are counterexamples both before and after the selected sentence in the video, where the packet lengths do not exhibit a continuous growth pattern.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b9ffcff5-6f4a-4fe1-aada-036f479eb245" />

Given this, I have a few questions:

  1. How did you determine the starting packet corresponding to the first sentence of LLM‘s reply?

  2. What strategy did you use to handle the subsequent packets, especially when their lengths do not follow a continuous growth pattern?
  
  3. Why is the difference in length between consecutive application data packets divided by 2 when calculating token length, instead of using the raw difference directly? Can you provide some samples of traffic pcap for academic research reference?

  
Looking forward to your response, and thank you again for your valuable contribution!

**Comment by royweiss1** [comment]
Hi,

Thank you for your interest and for taking the time to study the paper and implementation. I’m happy to clarify your questions.

Firstly, it’s important to note that each vendor has unique ways of transmitting packets, with protocols and payloads evolving frequently. Consequently, building a universally applicable pipeline is challenging and impractical. With that context in mind, here are my responses to your questions:

1) Determining the Starting Packet
This varies across vendors. For the demo, we specifically studied the pattern of Microsoft Copilot and identified the starting point based on the observed packet sequence in the decrypted traffic. The pattern shown in the video is specific to this implementation, which we deduced by examining the traffic. If you're interested, you can perform a similar analysis on the decrypted traffic to uncover the patterns yourself.

2) Handling Subsequent Packets
Our approach primarily involves calculating the delta in packet lengths. However, this process is not without challenges. For example, noise in the data—such as acknowledgment (ACK) packets from the same server, which are typically small—or issues like Maximum Transition Size (MTS) overflow can complicate the analysis. As noted in the README, we didn’t aim to build a fully generalized pipeline, given these inherent complexities and the variability between vendors.

3) Why Divide by Two for Token Length Calculation?
Some vendors include new tokens twice within the transmitted JSON payload for reasons that remain unclear. This results in the observed size increase being double the actual token size. While I don’t recall which vendor exhibited this behavior, it can be verified through analysis of the decrypted traffic if you're curious to investigate further.

Finally, I encourage you to conduct your own reverse engineering on the decrypted traffic for further exploration. This hands-on approach will provide deeper insights and help adapt the methodology to your specific use case.

Please feel free to reach out if you have any further questions—I’m happy to assist.

Best regards,
Roy

**Comment by CigarOVO** [comment]
Hi Roy,

Thank you for your detailed and thoughtful response! I appreciate the clarification, especially regarding the challenges involved in working with encrypted traffic and the decryption approach you used for your analysis.

I have a follow-up question regarding the decryption of encrypted communication from LLM vendors. Given that most service providers now transmit traffic using encryption,  how can we obtain decrypted traffic for analysis from these vendors, in a manner similar to how you “studied the pattern of Microsoft Copilot and identified the starting point based on the observed packet sequence in the decrypted traffic” in your study?

Are there any tools, techniques, or specific strategies you would recommend for capturing and decrypting traffic, or handling the encryption process in a way that facilitates pattern analysis and reverse engineering?

Looking forward to hearing your thoughts on this!

Best regards

**Comment by CigarOVO** [comment]
Thank you so much for your prompt and insightful response, as well as for sharing the helpful guide! Your explanation has greatly enhanced my understanding of the approaches and experiments described in your work. 

Wish you have a good day!
